name: CI-CD workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    build:
      runs-on: ubuntu-latest
      container: python:3.9-slim
    
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Log in to IBM Cloud Container Registry
          uses: docker/login-action@v1
          with:
            registry: us.icr.io
            username: ${{ secrets.IBM_CLOUD_REGISTRY_USERNAME }}
            password: ${{ secrets.IBM_CLOUD_REGISTRY_API_KEY }}
    
        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: us.icr.io/ibm1234/my-image:${{ github.sha }}
